#
# Module manifest for module 'ISEPSProject'
#
# Generated by: Christopher J. Maahs
#
# Generated on: 12/28/2016
#

@{

# Script module or binary module file associated with this manifest.
RootModule = '.\ISEPSProject.psm1'

# Version number of this module.
ModuleVersion = '1.3.13'

# ID used to uniquely identify this module
GUID = 'f041d119-4241-4d6b-bdf4-ab1e308542e2'

# Author of this module
Author = 'Christopher J. Maahs'

# Company or vendor of this module
CompanyName = 'Christopher J. Maahs Consulting'

# Copyright statement for this module
Copyright = '(c) 2016 Christopher J. Maahs. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Set of cmdlets used to manage Powershell projects within ISE'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module
FunctionsToExport = @('Add-PspSourceToPowershellProject','Close-PspPowershellProject','Get-PspPowershellProject','=','New-PspPowershellProject','Open-PspPowershellProject','Remove-PspSourceFromPowershellProject','Repair-PspPowershellProject','Set-PspIncludeInBuildFlagForSource','Set-PspPowershellProjectDefaults','Set-PspReadMeOrderForSource','Start-PspBuildPowershellProject','Start-PspBuildSourceFileFromPowershellProject','Start-PspDeployPowershellProject','Compare-PspPowershellProjectBackup','Get-PspPowershellProjectBackup','Restore-PspPowershellProjectBackup','Get-PspRelativePathFromProjectRoot','Start-IsePsPublishToEvcNuGet','Get-PspPowershellProjectDefaults','New-PspIsePsZipInstallDetails','Get-PspPowershellProjectFilesNotIncludedInProject','Get-PspPowershellProjectFunctions','Set-Psp','Start-Psp')

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @()

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = @'
1.3.13 - Adding verbose to help build.
1.3.12 - Fixing some errors in build.
1.3.11 - Attempting to fix the removal of the ./bin/ directory during build.
1.3.9  - Fixing Module Init all being on ONE line at the end of the IncludeStyle psm1 file.        
1.3.8  - Adding a function to automate the build and install specifically for Veritas networks.
1.3.7  - Add Missing Files from Product functionality.
1.3.6  - SingleFile type was only including a single file in the README.md file.
1.3.5  - add Out-String to Get-Help for building README.md file.
1.3.4  - fix a singlefile format build error.
1.3.3  - Final fix on Pipeline, and deploy of about*.txt files for Languages.
1.3.2  - fixing some Pipeline stuff and naming convention.
1.3.1  - Cleanup of PINC and Documentation
1.2.9  - Change the way we pull documentation for the README.md file.
1.2.8  - Add support to pull interior function documentation for README.md file.
1.2.7  - Adding support to extract ZIP files during the build/deploy process.
Added sub-directory support.  TAB names will be based off of sub-directory names from the project root directory.
'@

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


